-- ─────────────────────────────────────────────────────────────────────────────
-- SwiftPOS Tech Access & Mode Switch — Database Migration
-- ─────────────────────────────────────────────────────────────────────────────

-- Tech access tokens
-- Generated by admin portal, verified offline by desktop app using HMAC-SHA256.
-- Scope: 48h, branch-specific, tech-specific.
CREATE TABLE IF NOT EXISTS public.tech_access_tokens (
  id              uuid        NOT NULL DEFAULT uuid_generate_v4(),
  admin_id        uuid        NOT NULL,               -- which tech generated this
  admin_name      text        NOT NULL,               -- snapshot
  business_id     uuid        NOT NULL,
  branch_id       uuid        NOT NULL,
  branch_name     text        NOT NULL,               -- snapshot
  token_hash      text        NOT NULL UNIQUE,        -- SHA-256 of the raw token
  expires_at      timestamptz NOT NULL,               -- always iat + 48h
  used_at         timestamptz,                        -- first use timestamp
  revoked_at      timestamptz,                        -- set if admin revokes
  revoked_by      text,                               -- admin email
  confirmed_at    timestamptz,                        -- admin clicks "confirm"
  status          text        NOT NULL DEFAULT 'active'
                  CHECK (status IN ('active','used','revoked','expired')),
  created_at      timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT tech_access_tokens_pkey       PRIMARY KEY (id),
  CONSTRAINT tech_access_tokens_admin_fk   FOREIGN KEY (admin_id)   REFERENCES public.admin_users(id),
  CONSTRAINT tech_access_tokens_biz_fk     FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT tech_access_tokens_branch_fk  FOREIGN KEY (branch_id)  REFERENCES public.branches(id)
);

-- Tracks whether a tech's previous access was ever confirmed.
-- If last_unconfirmed_at is set and > 48h ago, next request requires manual approval.
CREATE TABLE IF NOT EXISTS public.tech_approval_flags (
  admin_id              uuid        NOT NULL,
  last_unconfirmed_at   timestamptz,    -- set when a token expires without confirmation
  requires_manual       boolean     NOT NULL DEFAULT false,
  updated_at            timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT tech_approval_flags_pkey  PRIMARY KEY (admin_id),
  CONSTRAINT tech_approval_flags_fk    FOREIGN KEY (admin_id) REFERENCES public.admin_users(id)
);

-- Mode switch requests
-- Admin generates a signed one-time token. Tech applies it on site.
-- Once applied the token is consumed and the switch is recorded.
CREATE TABLE IF NOT EXISTS public.mode_switch_requests (
  id              uuid        NOT NULL DEFAULT uuid_generate_v4(),
  business_id     uuid        NOT NULL,
  branch_id       uuid        NOT NULL,
  from_mode       text        NOT NULL CHECK (from_mode IN ('local','cloud')),
  to_mode         text        NOT NULL CHECK (to_mode   IN ('local','cloud')),
  token_hash      text        NOT NULL UNIQUE,
  generated_by    text        NOT NULL,               -- admin email
  approved_by     text,                               -- can be same as generated_by
  status          text        NOT NULL DEFAULT 'pending'
                  CHECK (status IN ('pending','applied','expired','cancelled')),
  -- Migration audit — filled when token is applied on site
  orders_migrated integer,
  applied_at      timestamptz,
  applied_by_tech text,
  notes           text,
  expires_at      timestamptz NOT NULL,               -- 7 days — tech has a week to do the visit
  created_at      timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT mode_switch_requests_pkey   PRIMARY KEY (id),
  CONSTRAINT mode_switch_requests_biz_fk FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT mode_switch_requests_br_fk  FOREIGN KEY (branch_id)   REFERENCES public.branches(id)
);

-- Branch deployment mode — the authoritative record of how a branch is deployed
ALTER TABLE public.branches
  ADD COLUMN IF NOT EXISTS deploy_mode   text NOT NULL DEFAULT 'cloud'
                                         CHECK (deploy_mode IN ('local','cloud')),
  ADD COLUMN IF NOT EXISTS mode_switched_at  timestamptz,
  ADD COLUMN IF NOT EXISTS mode_switched_by  text;

-- Indexes
CREATE INDEX IF NOT EXISTS idx_tech_tokens_branch   ON public.tech_access_tokens (branch_id, status);
CREATE INDEX IF NOT EXISTS idx_tech_tokens_admin    ON public.tech_access_tokens (admin_id);
CREATE INDEX IF NOT EXISTS idx_tech_tokens_expires  ON public.tech_access_tokens (expires_at);
CREATE INDEX IF NOT EXISTS idx_mode_switch_branch   ON public.mode_switch_requests (branch_id, status);
