import { Router } from 'express';

import authRoutes          from './auth';
import businessRoutes      from './business';
import onboardingRoutes    from './onboarding';
import categoriesRoutes    from './categories';
import productsRoutes      from './products';
import posRoutes           from './pos';
import variantsRoutes      from './variants';
import modifiersRoutes     from './modifiers';
import ordersRoutes        from './orders';
import inventoryRoutes     from './inventory';
import kitchenRoutes       from './kitchen';
import staffRoutes         from './staff';
import reportsExportRoutes from './reports-export';
import reportsRoutes       from './reports';
import loyaltyRoutes       from './loyalty';
import creditRoutes        from './credit';
import notificationsRoutes from './notifications';
import branchesRoutes      from './branches';
import discountsRoutes     from './discounts';
import promotionsRoutes    from './promotions';
import flagsRoutes         from './flags';
import tablesRoutes        from './tables';
import shiftsRoutes        from './shifts';
import stockRoutes         from './stock';
import expensesRoutes      from './expenses';
import recipesRoutes       from './recipes';
import printersRoutes      from './printers';
import mpesaRoutes         from './mpesa';
import webhooksRoutes      from './webhooks';
import { fuelTanksRouter, pumpsRouter } from './fueltanks';
import combosRoutes        from './combos';
import reservationsRoutes  from './reservations';
import qrRoutes            from './qr';
import etimsRoutes         from './etims';
import adminRoutes         from './admin';
import techRoutes          from './tech';
import syncRoutes          from './sync';
import devicesRoutes       from './devices';
import parkingRoutes       from './parking';
import branchPricesRoutes  from './branch-prices';

const router = Router();

router.use('/auth',           authRoutes);
router.use('/branches',       branchesRoutes);
router.use('/discounts',      discountsRoutes);
router.use('/promotions',     promotionsRoutes);
router.use('/combos',         combosRoutes);
router.use('/reservations',   reservationsRoutes);
router.use('/qr',             qrRoutes);
router.use('/flags',          flagsRoutes);
router.use('/tables',         tablesRoutes);
router.use('/shifts',         shiftsRoutes);
router.use('/stock',          stockRoutes);
router.use('/expenses',       expensesRoutes);
router.use('/recipes',        recipesRoutes);
router.use('/printers',       printersRoutes);
router.use('/business',       businessRoutes);
router.use('/onboarding',     onboardingRoutes);
router.use('/categories',     categoriesRoutes);
router.use('/products',       productsRoutes);
router.use('/branch-prices',  branchPricesRoutes);
router.use('/pos',            posRoutes);
router.use('/variants',       variantsRoutes);
router.use('/modifiers',      modifiersRoutes);
router.use('/orders',         ordersRoutes);
router.use('/inventory',      inventoryRoutes);
router.use('/kitchen',        kitchenRoutes);
router.use('/staff',          staffRoutes);
router.use('/loyalty',        loyaltyRoutes);
router.use('/credit',         creditRoutes);
router.use('/notifications',  notificationsRoutes);
router.use('/webhooks',       webhooksRoutes);
router.use('/mpesa',          mpesaRoutes);
router.use('/fuel-tanks',     fuelTanksRouter);
router.use('/pumps',          pumpsRouter);
router.use('/etims',          etimsRoutes);

// IMPORTANT: reports/export must come before /reports
router.use('/reports/export', reportsExportRoutes);
router.use('/reports',        reportsRoutes);

router.use('/admin',          adminRoutes);
router.use('/tech',           techRoutes);
router.use('/sync',           syncRoutes);
router.use('/devices',        devicesRoutes);
router.use('/parking-sessions', parkingRoutes);

export default router;
