/**
 * /api/tech — SwiftPOS Tech Access Routes
 * ─────────────────────────────────────────────────────────────────────────────
 * These routes are called by the desktop app's hidden tech panel.
 * Authentication uses HMAC-signed offline tokens generated by the admin portal.
 * All verification is designed to work without internet on the local server.
 *
 * Routes:
 *   POST /api/tech/verify-token     — verify offline tech token, open session
 *   GET  /api/tech/status           — system diagnostics
 *   GET  /api/tech/logs             — recent server errors
 *   GET  /api/tech/sync-status      — pending orders, last sync time
 *   POST /api/tech/mode-switch/apply — apply a mode switch token with migration
 */

import { Router }    from 'express';
import { sendError } from '../lib/sendError';
import { safeRouter } from '../middleware/asyncHandler';
import { supabase }  from '../lib/supabase';
import { requireAuth } from '../middleware/auth';
import { verifyTechToken as verifyEd25519Token, PUBLIC_KEY_PEM } from '../lib/techToken';
import crypto        from 'crypto';
import os            from 'os';
import { execSync }  from 'child_process';

const router = safeRouter();

// No fallback: an unset secret must stop the server booting, never silently
// fall back to a value that is published in source control (which would let
// anyone forge a v1 tech token). Mirrors JWT_SECRET / ADMIN_JWT_SECRET handling.
const TECH_HMAC_SECRET = process.env.TECH_HMAC_SECRET;
if (!TECH_HMAC_SECRET) {
  throw new Error('[server] Missing TECH_HMAC_SECRET in environment');
}

// ── In-memory revocation cache ─────────────────────────────────────────────
// Refreshed from DB every 5 minutes so revocations propagate to offline machines
// on their next restart. Good enough — tech tokens are 48h, revocation is rare.
let revokedHashes = new Set<string>();
let lastRevocationRefresh = 0;

async function refreshRevocations() {
  const now = Date.now();
  if (now - lastRevocationRefresh < 5 * 60 * 1000) return;
  lastRevocationRefresh = now;
  try {
    const { data } = await supabase
      .from('tech_access_tokens')
      .select('token_hash')
      .eq('status', 'revoked')
      .gte('expires_at', new Date().toISOString()); // only unexpired ones matter
    revokedHashes = new Set((data ?? []).map((r: any) => r.token_hash));
  } catch { /* non-fatal — cache stays stale */ }
}

// ── Token helpers ──────────────────────────────────────────────────────────

/** Verify a raw tech token. Returns decoded payload or null.
 *  Supports v2 Ed25519 tokens (st2.*, offline-verifiable) and legacy v1 HMAC. */
function verifyTechToken(rawToken: string): {
  techId: string; techName: string; branchId: string;
  businessId: string; scope: string; exp: number;
} | null {
  // v2 — Ed25519 (asymmetric). Same verifier the desktop uses offline.
  if (rawToken.startsWith('st2.')) {
    const p = verifyEd25519Token(rawToken);
    return p ? { techId: p.techId, techName: p.techName, branchId: p.branchId, businessId: p.businessId, scope: p.scope, exp: p.exp } : null;
  }
  // v1 — legacy HMAC (online-only). Format: base64(payload).signature
  try {
    const lastDot  = rawToken.lastIndexOf('.');
    const payload  = rawToken.slice(0, lastDot);
    const sig      = rawToken.slice(lastDot + 1);
    const expected = crypto.createHmac('sha256', TECH_HMAC_SECRET).update(payload).digest('hex');
    const sigBuf      = Buffer.from(sig, 'hex');
    const expectedBuf = Buffer.from(expected, 'hex');
    // Length guard: timingSafeEqual throws RangeError on unequal-length buffers,
    // which a malformed/attacker-supplied signature can trigger. Compare lengths
    // first so a bad signature is a clean reject, not an exception.
    if (sigBuf.length !== expectedBuf.length) return null;
    if (!crypto.timingSafeEqual(sigBuf, expectedBuf)) return null;
    return JSON.parse(Buffer.from(payload, 'base64url').toString());
  } catch { return null; }
}

// ── Middleware ─────────────────────────────────────────────────────────────

async function requireTechToken(req: any, res: any, next: any) {
  const raw = req.headers['x-tech-token'] as string;
  if (!raw) { res.status(401).json({ error: 'Tech token required', code: 'TECH_TOKEN_MISSING' }); return; }

  const payload = verifyTechToken(raw);
  if (!payload) { res.status(401).json({ error: 'Invalid tech token', code: 'TECH_TOKEN_INVALID' }); return; }

  if (Date.now() / 1000 > payload.exp) {
    res.status(401).json({ error: 'Tech token has expired', code: 'TECH_TOKEN_EXPIRED' }); return;
  }

  // Check revocation cache
  await refreshRevocations();
  const tokenHash = crypto.createHash('sha256').update(raw).digest('hex');
  if (revokedHashes.has(tokenHash)) {
    res.status(403).json({ error: 'Tech token has been revoked', code: 'TECH_TOKEN_REVOKED' }); return;
  }

  req.techPayload = payload;
  req.tokenHash   = tokenHash;

  // Mark first use in DB (non-blocking)
  supabase.from('tech_access_tokens')
    .update({ used_at: new Date().toISOString(), status: 'used' })
    .eq('token_hash', tokenHash)
    .is('used_at', null)
    .then(() => {}).catch(() => {});

  next();
}

// ── POST /api/tech/verify-token ────────────────────────────────────────────
// Desktop calls this on tech login. Returns the decoded payload so the
// tech panel knows who is logged in and which branch is authorised.

router.post('/verify-token', async (req, res) => {
  const { token } = req.body;
  if (!token) { res.status(400).json({ error: 'token is required' }); return; }

  const payload = verifyTechToken(token);
  if (!payload) { res.status(401).json({ error: 'Invalid token', code: 'TECH_TOKEN_INVALID' }); return; }
  if (Date.now() / 1000 > payload.exp) {
    res.status(401).json({ error: 'Token expired', code: 'TECH_TOKEN_EXPIRED' }); return;
  }

  await refreshRevocations();
  const tokenHash = crypto.createHash('sha256').update(token).digest('hex');
  if (revokedHashes.has(tokenHash)) {
    res.status(403).json({ error: 'Token revoked', code: 'TECH_TOKEN_REVOKED' }); return;
  }

  res.json({
    valid:       true,
    techId:      payload.techId,
    techName:    payload.techName,
    branchId:    payload.branchId,
    businessId:  payload.businessId,
    expiresAt:   new Date(payload.exp * 1000).toISOString(),
  });
});

// ── GET /api/tech/public-key ───────────────────────────────────────────────
// The Ed25519 public key the desktop uses to verify tech tokens OFFLINE. A
// public key is not secret — it can only verify, never sign. Open endpoint so a
// device can refresh the key if it's ever rotated.
router.get('/public-key', async (_req, res) => {
  res.json({ algorithm: 'ed25519', public_key: PUBLIC_KEY_PEM });
});

// ── GET /api/tech/branch-config/:branchId ──────────────────────────────────
// Called by the desktop at ACTIVATION (owner-authenticated) to cache everything
// it needs to gate tech access offline thereafter: the branch's reveal code
// (doorknock) and the token-verification public key. Scoped to the owner's own
// business so one business can't read another's reveal code.
router.get('/branch-config/:branchId', requireAuth, async (req: any, res) => {
  const branchId = String(req.params.branchId);
  const { data: branch } = await supabase
    .from('branches')
    .select('id, name, business_id, tech_reveal_code')
    .eq('id', branchId)
    .single();

  if (!branch)                              { res.status(404).json({ error: 'Branch not found' }); return; }
  if (branch.business_id !== req.businessId) { res.status(403).json({ error: 'Branch not in your business' }); return; }

  res.json({
    branch_id:   branch.id,
    reveal_code: branch.tech_reveal_code ?? null,
    public_key:  PUBLIC_KEY_PEM,
    algorithm:   'ed25519',
  });
});

// ── POST /api/tech/audit ───────────────────────────────────────────────────
// Records a tech action for the audit trail (who/where/what/when + device). The
// desktop queues these locally while offline and flushes them here when it can
// reach the server. Authenticated by the tech token itself.
router.post('/audit', requireTechToken, async (req: any, res) => {
  const { action, device_id, detail, occurred_at } = req.body ?? {};
  const { techId, techName, branchId, businessId } = req.techPayload;
  if (!action) { res.status(400).json({ error: 'action is required' }); return; }

  const { error } = await supabase.from('tech_audit_log').insert({
    tech_id:     techId,
    tech_name:   techName,
    business_id: businessId,
    branch_id:   branchId,
    device_id:   device_id ?? null,
    action:      String(action).slice(0, 120),
    detail:      detail ?? null,
    occurred_at: occurred_at ?? new Date().toISOString(),
    token_hash:  req.tokenHash ?? null,
  });
  if (error) { sendError(res, error); return; }
  res.json({ ok: true });
});

// ── GET /api/tech/status ───────────────────────────────────────────────────
// System diagnostics visible to the tech. No customer data exposed.

router.get('/status', requireTechToken, async (req: any, res) => {
  const { branchId, businessId } = req.techPayload;

  const [
    { data: branch },
    { data: business },
    { count: pendingOrders },
    { count: totalOrders },
    { data: lastOrder },
    { data: lastShift },
  ] = await Promise.all([
    supabase.from('branches').select('id, name, deploy_mode, desktop_licensed, mode_switched_at').eq('id', branchId).single(),
    supabase.from('businesses').select('id, name, type, status').eq('id', businessId).single(),
    supabase.from('orders').select('*', { count: 'exact', head: true }).eq('branch_id', branchId).eq('sync_status', 'pending'),
    supabase.from('orders').select('*', { count: 'exact', head: true }).eq('branch_id', branchId),
    supabase.from('orders').select('created_at, status').eq('branch_id', branchId).order('created_at', { ascending: false }).limit(1).maybeSingle(),
    supabase.from('shifts').select('opened_at, closed_at, status').eq('branch_id', branchId).order('opened_at', { ascending: false }).limit(1).maybeSingle(),
  ]);

  res.json({
    server: {
      version:    process.env.npm_package_version ?? '1.0.0',
      node:       process.version,
      platform:   process.platform,
      uptime_s:   Math.floor(process.uptime()),
      memory_mb:  Math.round(process.memoryUsage().rss / 1024 / 1024),
      hostname:   os.hostname(),
    },
    branch: {
      id:              branch?.id,
      name:            branch?.name,
      deploy_mode:     branch?.deploy_mode ?? 'cloud',
      desktop_licensed: branch?.desktop_licensed,
      mode_switched_at: branch?.mode_switched_at,
    },
    business: {
      id:     business?.id,
      name:   business?.name,
      type:   business?.type,
      status: business?.status,
    },
    sync: {
      pending_orders: pendingOrders ?? 0,
      total_orders:   totalOrders ?? 0,
      last_order_at:  lastOrder?.created_at ?? null,
    },
    shift: {
      status:    lastShift?.status ?? 'none',
      opened_at: lastShift?.opened_at ?? null,
      closed_at: lastShift?.closed_at ?? null,
    },
  });
});

// ── GET /api/tech/sync-status ──────────────────────────────────────────────

router.get('/sync-status', requireTechToken, async (req: any, res) => {
  const { branchId } = req.techPayload;

  const [
    { count: pendingCount, data: pendingSample },
    { count: failedCount },
    { count: syncedCount },
  ] = await Promise.all([
    supabase.from('orders').select('id, order_number, created_at', { count: 'exact' })
      .eq('branch_id', branchId).eq('sync_status', 'pending').limit(5).order('created_at', { ascending: false }),
    supabase.from('orders').select('*', { count: 'exact', head: true })
      .eq('branch_id', branchId).eq('sync_status', 'failed'),
    supabase.from('orders').select('*', { count: 'exact', head: true })
      .eq('branch_id', branchId).eq('sync_status', 'synced'),
  ]);

  res.json({
    pending:  pendingCount ?? 0,
    failed:   failedCount  ?? 0,
    synced:   syncedCount  ?? 0,
    sample:   pendingSample ?? [],
  });
});

// ── POST /api/tech/mode-switch/apply ──────────────────────────────────────
// The most critical endpoint. Applies a mode switch token with full migration.
//
// The migration logic guarantees zero duplicate orders using idempotency_key:
//
//   LOCAL → CLOUD:
//     1. All local pending orders are pushed to cloud with their idempotency_key
//     2. Cloud uses ON CONFLICT (idempotency_key) DO NOTHING
//     3. Branch deploy_mode updated to 'cloud'
//
//   CLOUD → LOCAL:
//     1. All cloud orders for this branch are available in the response
//        for the desktop app to import into SQLite
//     2. Branch deploy_mode updated to 'local'
//     3. Cloud will return 410 Gone for future writes from this branch
//        (the desktop app reads this and switches API_URL to local)

router.post('/mode-switch/apply', requireTechToken, async (req: any, res) => {
  const { switch_token, tech_name } = req.body;
  const { branchId, businessId }   = req.techPayload;

  if (!switch_token) { res.status(400).json({ error: 'switch_token is required' }); return; }

  // Hash and look up the switch token
  const switchHash = crypto.createHash('sha256').update(switch_token).digest('hex');

  const { data: switchReq, error: switchErr } = await supabase
    .from('mode_switch_requests')
    .select('*')
    .eq('token_hash', switchHash)
    .eq('branch_id', branchId)
    .eq('status', 'pending')
    .single();

  if (switchErr || !switchReq) {
    res.status(404).json({ error: 'Invalid or already-used switch token', code: 'SWITCH_TOKEN_INVALID' });
    return;
  }

  if (new Date(switchReq.expires_at) < new Date()) {
    res.status(410).json({ error: 'Switch token has expired', code: 'SWITCH_TOKEN_EXPIRED' });
    return;
  }

  // ── Gather orders that need migrating ────────────────────────────────────

  let ordersMigrated = 0;
  let cloudOrders: any[] = [];

  if (switchReq.to_mode === 'cloud') {
    // LOCAL → CLOUD: return list of pending orders for the desktop app to push
    const { data: pending } = await supabase
      .from('orders')
      .select(`
        id, order_number, order_type, status, subtotal, vat_amount,
        discount_amount, total, created_at, idempotency_key, covers, shift_id,
        customer_id, customer_name, customer_phone, table_number, notes,
        order_items ( product_id, product_name, category_name, unit_price, quantity, subtotal, notes ),
        payments ( method, amount, amount_tendered, change_given, reference, status )
      `)
      .eq('branch_id', branchId)
      .eq('sync_status', 'pending')
      .order('created_at');

    ordersMigrated = pending?.length ?? 0;
    // The desktop app will push these to the cloud API individually
    // with their idempotency_key. Server uses ON CONFLICT DO NOTHING.
    cloudOrders = pending ?? [];

  } else {
    // CLOUD → LOCAL: return ALL orders for this branch so desktop can seed SQLite
    const { data: all, count } = await supabase
      .from('orders')
      .select(`
        id, order_number, order_type, status, subtotal, vat_amount,
        discount_amount, total, created_at, idempotency_key, covers, shift_id,
        customer_id, customer_name, customer_phone, table_number, notes,
        order_items ( product_id, product_name, category_name, unit_price, quantity, subtotal, notes ),
        payments ( method, amount, amount_tendered, change_given, reference, status )
      `, { count: 'exact' })
      .eq('branch_id', branchId)
      .order('created_at');

    ordersMigrated = count ?? 0;
    cloudOrders = all ?? [];
  }

  // ── Apply the switch ─────────────────────────────────────────────────────

  await supabase.from('branches').update({
    deploy_mode:      switchReq.to_mode,
    mode_switched_at: new Date().toISOString(),
    mode_switched_by: tech_name ?? req.techPayload.techName,
    updated_at:       new Date().toISOString(),
  }).eq('id', branchId);

  // Consume the switch token
  await supabase.from('mode_switch_requests').update({
    status:          'applied',
    applied_at:      new Date().toISOString(),
    applied_by_tech: tech_name ?? req.techPayload.techName,
    orders_migrated: ordersMigrated,
  }).eq('id', switchReq.id);

  // Write admin audit log
  await supabase.from('admin_audit_log').insert({
    admin_id:      req.techPayload.techId,
    admin_email:   req.techPayload.techName,
    action:        `mode_switch.${switchReq.from_mode}_to_${switchReq.to_mode}`,
    resource:      'branch',
    business_id:   businessId,
    after_data:    { from: switchReq.from_mode, to: switchReq.to_mode, orders_migrated: ordersMigrated },
  });

  res.json({
    success:         true,
    from_mode:       switchReq.from_mode,
    to_mode:         switchReq.to_mode,
    orders_migrated: ordersMigrated,
    // Desktop app uses this to re-seed its SQLite or to push pending orders
    orders:          cloudOrders,
    // Desktop app should update its config.json with this
    new_config: {
      deploy_mode: switchReq.to_mode,
      sync_enabled: switchReq.to_mode === 'cloud',
    },
  });
});

export default router;
