directories:
  output: release
  buildResources: build
appId: com.swiftpos.desktop
productName: SwiftPOS
files:
  - filter:
      - dist/**/*
      - resources/**/*
linux:
  target:
    - AppImage
    - deb
win:
  target:
    - nsis
mac:
  target:
    - dmg
electronVersion: 35.7.5
